In [4]:
import numpy as np

In [5]:
a = np.random.randn(1,3)


In [6]:
b = np.random.randn(3,3)

In [7]:
a * b

array([[-0.06175323, -0.0853348 , -0.60878825],
       [-0.0617432 ,  1.02236261, -3.26961818],
       [ 0.13856343,  1.20841337, -0.16026748]])

In [8]:
a = np.random.randn(3,3)
b = np.random.rand(2,1)
a + b

ValueError: operands could not be broadcast together with shapes (3,3) (2,1) 

In [9]:
a = np.array([[2,1],[1,3]])
a*a

array([[4, 1],
       [1, 9]])

In [10]:
import math

In [11]:
np.zeros((2,1)).shape

(2, 1)

In [12]:
np.zeros(2)

array([0., 0.])

In [13]:
x = np.random.rand(4,5)

In [14]:
x

array([[0.28919968, 0.54781175, 0.42227021, 0.04739908, 0.5606886 ],
       [0.98045413, 0.86142225, 0.82485402, 0.53718362, 0.53079069],
       [0.7080064 , 0.46099401, 0.40508289, 0.0620262 , 0.12305729],
       [0.85626644, 0.89791348, 0.8377939 , 0.19867617, 0.88931842]])

In [15]:
y = np.sum(x,axis=1)

In [16]:
y

array([1.86736931, 3.73470472, 1.75916679, 3.67996841])

In [17]:
y.shape

(4,)