# NumPy Arrays

In [1]:
!pip install numPy

In [2]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3, 4, 5])

In [4]:
arr

array([1, 2, 3, 4, 5])

In [5]:
my_cat = [[1,2,3], [4,5,6], [7,8,9]]

In [6]:
np.array(my_cat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [8]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.linspace(0, 5, 5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [11]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
np.random.rand(5)

array([0.61230519, 0.99954197, 0.79247872, 0.45452806, 0.39028207])

In [13]:
np.random.rand(3,3)

array([[0.45412013, 0.03171471, 0.87066739],
       [0.80124397, 0.70946493, 0.16657326],
       [0.11790584, 0.94222155, 0.78564721]])

In [14]:
np.random.randn(2)

array([-0.46815195,  0.80145499])

In [15]:
np.random.randint(1,100)

46

In [16]:
arr = np.arange(25)

In [17]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [18]:
ranarr = np.random.randint(0, 50, 10)

In [19]:
ranarr

array([ 0, 48, 37, 13, 48, 17, 15, 31, 15, 43])

In [20]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [21]:
arr.max(), arr.min()

(np.int64(24), np.int64(0))

In [22]:
ranarr.argmax()  # index of the max value

np.int64(1)

In [23]:
ranarr.argmin()  # index of the min value

np.int64(0)

In [24]:
ranarr.shape

(10,)

## NumPy Indexing and Selection

In [25]:
arr = np.arange(0,11) # create 1-dimentional array from 0 to 10

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
arr[1]

np.int64(1)

In [28]:
arr[1:5]

array([1, 2, 3, 4])

In [29]:
arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [30]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [31]:
arr[0:5] = 100

In [32]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [33]:
slice_of_arr = arr[0:6]

In [34]:
slice_of_arr

array([100, 100, 100, 100, 100,   5])

In [35]:
arr_copy = arr.copy()

In [36]:
arr_copy

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [37]:
arr_copy[:] = 100

In [38]:
arr_copy # initial arr remains unchanged

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [39]:
#### 2D array

arr_2d = np.array([[5,10,15], [20,25,30], [35,40,45]])

In [40]:
print(arr_2d, arr_2d.shape)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]] (3, 3)


In [41]:
arr_2d[0][0]

np.int64(5)

In [42]:
arr_2d[0]

array([ 5, 10, 15])

In [43]:
print(arr_2d[1][1], arr_2d[1,1]) # both work

25 25


In [44]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [45]:
arr = np.arange(1,11)

In [46]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
bool_arr = arr > 5 # boolean array: True for elements > 5, False otherwise

In [48]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [49]:
arr[bool_arr] # filtering using boolean array

array([ 6,  7,  8,  9, 10])

In [50]:
arr[arr > 5] # conditional selection   

array([ 6,  7,  8,  9, 10])

In [51]:
arr[arr < 3]

array([1, 2])

In [52]:
arr_2d = np.arange(50).reshape(5,10)

In [53]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [54]:
arr_2d[arr_2d > 20]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
       38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [55]:
arr_2d[:5,5:]

array([[ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29],
       [35, 36, 37, 38, 39],
       [45, 46, 47, 48, 49]])

In [56]:
arr_2d[2,0:5]

array([20, 21, 22, 23, 24])

In [57]:
arr_2d[-1,:7]

array([40, 41, 42, 43, 44, 45, 46])

In [58]:
arr_2d[1:4]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

## NumPy Opeartions

In [59]:
arr = np.arange(1,11)

In [60]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
arr + arr # addition    

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [62]:
arr * arr # multiplication

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [63]:
arr - arr # subtraction

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [64]:
arr + 100

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [65]:
arr - 1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
arr ** 2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [73]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [74]:
np.amax(arr)

np.int64(10)

In [ ]:
# An exponential function represents the relationship between an input and ouput,
# where we use repreated multiplication on an initial value to get the output for any 
# given input. Exponential can grow or decay very quickly.

# y = e^x --> `e`` is the natural base, `x` is the element in the array
print(arr, np.exp(arr))

[ 1  2  3  4  5  6  7  8  9 10] [2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04]


np.float64(20.085536923187668)